#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="cleaning.py",
        deps=ctx.path_to(ctx, "IN_DATA", "training_data/data.tsv"),
        target=ctx.path_to(ctx, "OUT_DATA", "data_clean.csv"),
        name="cleaning",
    )
