name: twitter_analysis

channels:
  - conda-forge
  - defaults
  - pytorch
  - gwerbin

dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab
  - numpy
  - pandas
  - pyarrow
  - scipy
  - scikit-learn

  - pip
  - python=3.7
  - python-graphviz

  - nb_conda_kernels

  - nltk
  - pytorch
  - torchtext
  - tensorboard
  - tensorboardx
  - seqeval
  - psutil
  - tqdm
  - spacy
  - spacy-model-en_core_sm

  - google-cloud-language
  - requests

  - git
  - gitpython

  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex

  - pre-commit

  - matplotlib
  - nbsphinx

  - pytest
  - pytest-cov

  - pip:
    - git+https://github.com/huggingface/transformers.git
    - tweet-preprocessor
    - textblob
    - vaderSentiment
    - stanfordnlp
    - stanfordcorenlp

    - spacy_cld  # not win32 compatible
    - spacymoji
