name: twitter_analysis
channels:
  - conda-forge
  - defaults
  - pytorch
  - gwerbin

dependencies:
  - ipykernel=5.1.3
  - ipython
  - ipywidgets
  - jupyterlab=1.1.4
  - numpy=1.16
  - pandas=0.25.1
  - scipy=1.2.1
  - scikit-learn

  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8

  - nb_conda_kernels=2.2.2

  - nltk
  - spacy
  - pytorch
  - torchtext
  - tensorboard
  - tensorboardx
  - seqeval
  - psutil
  - pyarrow
  - tqdm

  - google-cloud-language
  - requests

  - git
  - gitpython

  - sphinx==2.2.0
  - sphinx-autobuild==0.7.1
  - sphinx_rtd_theme==0.4.3
  - sphinxcontrib-bibtex==1.0.0

  - click==7.0

  - pre-commit==1.18.3

  - matplotlib==3.1.1
  - nbsphinx==0.4.2
  - pytest==5.2.0
  - pytest-cov==2.7.1

  - pip:
    - git+https://github.com/huggingface/transformers.git
    - tweet-preprocessor
    - textblob
    - vaderSentiment
    - stanfordnlp
    - stanfordcorenlp
