def build(ctx):

    ctx(
        features="run_py_script",
        source="plot_favorite_sources.py",
        deps=ctx.path_to(ctx, "OUT_DATA", "data_clean.pkl"),
        target=ctx.path_to(ctx, "OUT_FIGURES", "fig-favorite-sources.png"),
        name="fig-favorite-sources",
    )

    ctx(
        features="run_py_script",
        source="plot_location_of_tweets.py",
        deps=ctx.path_to(ctx, "OUT_DATA", "data_clean.pkl"),
        target=[
            ctx.path_to(ctx, "OUT_FIGURES", "fig-location-cities.png"),
            ctx.path_to(ctx, "OUT_FIGURES", "fig-location-states.png"),
        ],
        name="fig-location",
    )
