#! python


def build(ctx):
    # ctx.recurse("library")
    ctx.recurse("data_management")  # basic data cleaning
    # ctx.recurse("pre_processing")  # pre-processing

    # ctx.recurse("model_train")  # model training
    # ctx.recurse("model_eval")  # model evaluation on new data

    # ctx.recurse("final")  # analyze of model evaluation results

    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    # ctx.add_group()
    # ctx.recurse("paper")
    # ctx.recurse("documentation")
